import "@/styles/globals.css";

import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";
import { Toaster } from "sonner";
import { Provider } from "@/components/Providers";
import ClerkProviderWithTheme from "@/components/ClerkProviderWithTheme";

export const metadata: Metadata = {
  title: "Collab-Sphere",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <Provider>
      <ClerkProviderWithTheme>
        <html lang="en" className={`${geist.variable}`}>
          <body>
            <TRPCReactProvider>{children}</TRPCReactProvider>
            <Toaster richColors />
          </body>
        </html>
      </ClerkProviderWithTheme>
    </Provider>
  );
}
